#!/bin/bash
# Example: Disaster Recovery Workflow
# Demonstrates how to restore from backups after data loss

set -euo pipefail

echo "═══════════════════════════════════════════════════════"
echo "Checkpoint - Disaster Recovery"
echo "═══════════════════════════════════════════════════════"
echo ""

echo "SCENARIO: You accidentally deleted important files or corrupted data"
echo ""

# Step 1: Assess the damage
echo "[1/6] Assess the Damage"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check what's available:"
echo "  /backup-restore --list"
echo ""
echo "Check backup status:"
echo "  /backup-status"
echo ""
read -p "Press Enter to continue..."

# Step 2: Review available backups
echo ""
echo "[2/6] Review Available Backups"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "List database backups:"
echo "  /backup-restore --list --database"
echo ""
echo "Example output:"
echo "  1) MyApp - 12.24.25 - 14:30.db.gz (1.2 MB) [30 min ago]"
echo "  2) MyApp - 12.24.25 - 13:30.db.gz (1.2 MB) [1 hour ago]"
echo "  3) MyApp - 12.24.25 - 12:30.db.gz (1.2 MB) [2 hours ago]"
echo ""
echo "Check file backups:"
echo "  ls -la backups/files/"
echo "  ls -la backups/archived/"
echo ""
read -p "Press Enter to continue..."

# Step 3: Restore database
echo ""
echo "[3/6] Restore Database"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 1: Interactive wizard"
echo "  /backup-restore"
echo "  Select: Database"
echo "  Choose snapshot from list"
echo ""
echo "Option 2: Direct restore (latest)"
echo "  /backup-restore --database latest"
echo ""
echo "Option 3: Specific snapshot"
echo "  /backup-restore --database \"12.24.25 - 13:30\""
echo ""
echo "Safety: Pre-restore backup created automatically at:"
echo "  backups/.pre-restore-TIMESTAMP/"
echo ""
read -p "Press Enter to continue..."

# Step 4: Restore specific files
echo ""
echo "[4/6] Restore Specific Files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Restore single file (current version):"
echo "  /backup-restore --file src/app.py"
echo ""
echo "Restore specific version:"
echo "  # List versions first"
echo "  ls -la backups/archived/src/app.py.*"
echo ""
echo "  # Restore specific version"
echo "  /backup-restore --file src/app.py --version 20251223_143000"
echo ""
echo "Restore multiple files:"
echo "  /backup-restore --file .env"
echo "  /backup-restore --file credentials.json"
echo "  /backup-restore --file config.yaml"
echo ""
read -p "Press Enter to continue..."

# Step 5: Verify restoration
echo ""
echo "[5/6] Verify Restoration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check git status:"
echo "  git status"
echo ""
echo "Test database:"
echo "  sqlite3 /path/to/db.db \"SELECT COUNT(*) FROM main_table;\""
echo ""
echo "Test application:"
echo "  python src/app.py"
echo "  # or whatever your run command is"
echo ""
echo "Check logs:"
echo "  tail -f backups/backup.log"
echo ""
read -p "Press Enter to continue..."

# Step 6: Resume backups
echo ""
echo "[6/6] Resume Normal Operations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Force new backup to capture current state:"
echo "  /backup-now --force"
echo ""
echo "Check system health:"
echo "  /backup-status"
echo ""
echo "Monitor for 24 hours:"
echo "  /backup-status --json > recovery-status.json"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "Recovery Complete!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Post-Recovery Checklist:"
echo "  ✅ Database restored and functional"
echo "  ✅ Critical files restored"
echo "  ✅ Application tested and working"
echo "  ✅ New backup created post-recovery"
echo "  ✅ Monitoring resumed"
echo ""
echo "Pre-restore backups saved at:"
echo "  backups/.pre-restore-*/"
echo ""
echo "These can be removed after confirming recovery:"
echo "  rm -rf backups/.pre-restore-*"
echo ""
echo "Consider:"
echo "  - Reviewing what caused the data loss"
echo "  - Adjusting retention policies if needed"
echo "  - Testing recovery process regularly"
echo ""
